// Leg three of the loop: derivation. The glossary people read is generated from
// the domain files, so it cannot describe terms that no longer exist.

export function renderGlossary(loaded, { generatedBy = "ontology-ops report" } = {}) {
  const domains = loaded
    .filter((d) => d.doc && !d.parseError)
    .sort((a, b) => (a.doc.metadata?.name ?? "").localeCompare(b.doc.metadata?.name ?? ""));

  const lines = [];
  lines.push("# Glossary");
  lines.push("");
  lines.push(`Generated by \`${generatedBy}\` from \`domains/\`. Do not edit by hand —`);
  lines.push("edit the domain files and regenerate, or the two will disagree and the");
  lines.push("hand-edited one will win in someone's memory.");
  lines.push("");

  const termCount = domains.reduce((n, d) => n + (d.doc.terms?.length ?? 0), 0);
  lines.push(`**${termCount} terms across ${domains.length} domains.**`);
  lines.push("");

  lines.push("| Term | Domain | Version | Owner | Definition |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const { doc } of domains) {
    const m = doc.metadata ?? {};
    for (const term of doc.terms ?? []) {
      lines.push(
        `| \`${term.name}\` | ${m.name ?? "—"} | ${m.version ?? "—"} | ${m.owner ?? "—"} | ${escapeCell(term.summary)} |`,
      );
    }
  }
  lines.push("");

  for (const { doc } of domains) {
    const m = doc.metadata ?? {};
    lines.push(`## ${m.name ?? "(unnamed domain)"} \`v${m.version ?? "?"}\``);
    lines.push("");
    lines.push(`Owner: **${m.owner ?? "unassigned"}**`);
    lines.push("");
    for (const term of doc.terms ?? []) {
      lines.push(`### ${term.name}`);
      lines.push("");
      lines.push(term.summary ?? "_no definition_");
      lines.push("");
      if (term.exclusions?.length) {
        lines.push(`**Excludes:** ${term.exclusions.map((x) => `\`${x}\``).join(", ")}`);
        lines.push("");
      }
      if (term.aliases?.length) {
        lines.push(`**Also called:** ${term.aliases.map((x) => `\`${x}\``).join(", ")}`);
        lines.push("");
      }
      if (term.mappings?.primarySource) {
        const filter = term.mappings.statusColumn ? ` where \`${term.mappings.statusColumn}\`` : "";
        lines.push(`**System of record:** \`${term.mappings.primarySource}\`${filter}`);
        lines.push("");
      }
    }
  }

  return lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

// Coverage signals worth seeing at a glance — the report's opinion about the
// health of the vocabulary, printed to the console rather than the file.
export function coverage(loaded) {
  const rows = [];
  for (const { doc, file } of loaded) {
    if (!doc?.terms) continue;
    const terms = doc.terms;
    const withMapping = terms.filter((t) => t.mappings?.primarySource).length;
    const withExclusions = terms.filter((t) => t.exclusions?.length).length;
    rows.push({
      domain: doc.metadata?.name ?? file,
      version: doc.metadata?.version ?? "—",
      terms: terms.length,
      grounded: withMapping,
      bounded: withExclusions,
    });
  }
  return rows;
}

const escapeCell = (s) => String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
